title: Kirk Saylor # your name (or website title) here
logo: "/images/ecotope_logO.gif" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD student, University of Maryland, Baltimore County
  <br><br>
  Dept. of Geography and Environmental Systems
  <br><br>
  <a href="https://www.researchgate.net/profile/Kirk_Saylor2">View My ResearchGate Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
